version: '3'

services:
  app:
    build:
      context: .
      args:
        TIMEZONE: Europe/Warsaw
    restart: on-failure
    volumes:
      - ./scripts/src:/var/www/html
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=interview
      - MYSQL_USERNAME=interview
      - MYSQL_PASSWORD=interview-password
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my_network

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USERNAME=interview
      - MYSQL_PASSWORD=interview-password
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Europe/Warsaw
    healthcheck:
      test: mysqladmin ping -u $$MYSQL_USERNAME --password=$$MYSQL_PASSWORD -h 127.0.0.1
      timeout: 20s
      retries: 10
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./scripts/mysql:/docker-entrypoint-initdb.d
    networks:
      - my_network


  tests:
    build:
      context: .
      args:
        TIMEZONE: Europe/Warsaw
    restart: on-failure
    volumes:
      - ./scripts/src:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "
      php artisan test
      "
    networks:
      - my_network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - my_network

networks:
  my_network:
    driver: bridge